{
    "openapi": "3.0.0",
    "info": {
        "title": "Fitzen Studios API's Docs.",
        "version": "1.0"
    },
    "servers": [
        {
            "url": "http://fitzen.test/api",
            "description": "Local 1"
        },
        {
            "url": "http://service.demowebsitelinks.com:3004/api",
            "description": "Staging"
        },
        {
            "url": "https://fitzen.studio/api",
            "description": "Live"
        }
    ],
    "paths": {
        "/register": {
            "post": {
                "tags": [
                    "Auth (Register, Login)"
                ],
                "parameters": [
                    {
                        "name": "time_zone",
                        "in": "query",
                        "description": "Options: ['Asia/Kolkata', 'America/Los_Angeles', 'America/Chicago', 'America/New_York']"
                    }
                ],
                "summary": "Register a new user.",
                "operationId": "route-register",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "first_name": "Cedric",
                                    "last_name": "Maya",
                                    "email": "asd441@mailinator.com",
                                    "password": "admin!@#",
                                    "phone": "1234",
                                    "time_zone": "Asia/Kolkata"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200" : {
                        "description": "success",
                        "content": {
                            "application/json": {

                            }
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "tags": [
                    "Auth (Register, Login)"
                ],
                "summary": "Login user.",
                "operationId": "route-login",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "email": "asd441@mailinator.com",
                                    "password": "admin!@#"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200" : {
                        "description": "success",
                        "content": {
                            "application/json": {

                            }
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "tags": [
                    "Secured Routes"
                ],
                "summary": "Logged in user details.",
                "operationId": "route-me",
                "requestBody": {
                    "content": {
                        "application/json": {

                        }
                    }
                },
                "responses": {
                    "200" : {
                        "description": "success",
                        "content": {
                            "application/json": {

                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/sessions": {
            "get": {
                "tags": [
                    "Secured Routes"
                ],
                "summary": "Session list of logged in user.",
                "operationId": "route-sessions",
                "requestBody": {
                    "content": {
                        "application/json": {

                        }
                    }
                },
                "responses": {
                    "200" : {
                        "description": "success",
                        "content": {
                            "application/json": {

                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/reschedule-session": {
            "post": {
                "tags": [
                    "Secured Routes"
                ],
                "parameters": [
                    {
                        "name": "request_by_timezone",
                        "in": "query",
                        "description": "Options: ['Asia/Kolkata', 'America/Los_Angeles', 'America/Chicago', 'America/New_York']"
                    }
                ],
                "summary": "Reschedule request for session.",
                "operationId": "route-reschedule-session",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "session_id": 1,
                                    "request_by": "customer",
                                    "request_by_timezone": "Asia/Kolkata",
                                    "new_session_date": "12-4-2023",
                                    "new_session_time": "12:34 AM",
                                    "reason": "Family Emergency"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200" : {
                        "description": "success",
                        "content": {
                            "application/json": {

                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/join-zoom-meeting": {
            "post": {
                "tags": [
                    "Secured Routes"
                ],
                "summary": "Join zoom meeting of session",
                "operationId": "route-join-zoom-meeting",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "session_id": 1
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200" : {
                        "description": "success",
                        "content": {
                            "application/json": {

                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/profile-update": {
            "post": {
                "tags": [
                    "Secured Routes"
                ],
                "summary": "Update Profile",
                "operationId": "route-profile-update",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "user_id": 1,
                                    "first_name": "Name",
                                    "last_name": "Name",
                                    "phone": "1231 231 123",
                                    "dob": "12-12-12",
                                    "gender": "Male",
                                    "weight": "123",
                                    "residence": "abc example",
                                    "age": "24",
                                    "nationality": "U.S.",
                                    "city": "N.Y.C.",
                                    "timezone": "EST",
                                    "days": "14",
                                    "sessions_in_week": "10",
                                    "training_type": "Training Type",
                                    "trainer_id": 1
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200" : {
                        "description": "success",
                        "content": {
                            "application/json": {

                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/profile": {
            "get": {
                "tags": [
                    "Secured Routes"
                ],
                "summary": "Profile",
                "operationId": "route-profile",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "user_id": 1
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200" : {
                        "description": "success",
                        "content": {
                            "application/json": {

                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}
